(defproject cljs-gravity "0.1.0-SNAPSHOT"
	:description "ClojureScript Gravity Graph"
	:url "http://example.com/FIXME"
	:dependencies [[org.clojure/clojure "1.7.0"]
					[org.clojure/clojurescript "0.0-3308" :classifier "aot" :exclusion [org.clojure/data.json]]
					[org.clojure/data.json "0.2.6" :classifier "aot"]
					;;[servant "0.1.3"]
         ]
	:plugins [[lein-cljsbuild "1.1.0"]]
	:source-paths ["src"]
	:clean-targets ["out" "release" "target"]

	:cljsbuild {
		:builds [{
			:source-paths ["src"] 
			:compiler {
              	:main "gravity.core"
     			:output-to "out/gravity.js"
     			:output-dir "out"
     			:verbose false
        		:warnings false
				; Configure warnings generated by the Closure compiler. 
				:closure-warnings {:externs-validation :off}
    
				;:optimizations :whitespace
				:pretty-print true
     			:externs ["libs/three.min.js"
   						  "libs/d3.min.js"
   			 			  "libs/OrbitControls.js"
        				  "libs/stats.min.js"]
        		:source-map "out/gravity.js.map"
          		:repl-listen-port 9000}}]})